#!/bin/sh

date

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export BERT_BASE_DIR=../chinese_L-12_H-768_A-12
export WSDM_DIR=../data

CUDA_VISIBLE_DEVICES=0 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=156 --train_batch_size=32 --predict_batch_size=32 --learning_rate=2e-5 --num_train_epochs=5.0 --output_dir=../output/output_2e5_5epo_156ml_weighted_extra64_1layer156/ --do_predict=true --swap_input=false --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=156 >> ../log/2e5_5epo_156ml_weighted_extra64_1layer156.log 2>&1 &

CUDA_VISIBLE_DEVICES=1 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=156 --train_batch_size=32 --predict_batch_size=32 --learning_rate=2e-5 --num_train_epochs=5.0 --output_dir=../output/output_2e5_5epo_156ml_weighted_extra64_1layer156_si/ --do_predict=true --swap_input=true --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=156 >> ../log/2e5_5epo_156ml_weighted_extra64_1layer156_si.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=168 --train_batch_size=32 --predict_batch_size=32 --learning_rate=2e-5 --num_train_epochs=5.0 --output_dir=../output/output_2e5_5epo_168ml_weighted_extra64_1layer256/ --do_predict=true --swap_input=false --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=256 >> ../log/2e5_5epo_168ml_weighted_extra64_1layer256.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=168 --train_batch_size=32 --predict_batch_size=32 --learning_rate=2e-5 --num_train_epochs=5.0 --output_dir=../output/output_2e5_5epo_168ml_weighted_extra64_1layer256_si/ --do_predict=true --swap_input=true --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=256 >> ../log/2e5_5epo_168ml_weighted_extra64_1layer256_si.log 2>&1 &


CUDA_VISIBLE_DEVICES=4 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=176 --train_batch_size=32 --predict_batch_size=32 --learning_rate=2e-5 --num_train_epochs=4.0 --output_dir=../output/output_2e5_4epo_176ml_weighted_extra64_1layer256/ --do_predict=true --swap_input=false --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=256 >> ../log/2e5_4epo_176ml_weighted_extra64_1layer256.log 2>&1 &

CUDA_VISIBLE_DEVICES=5 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=176 --train_batch_size=32 --predict_batch_size=32 --learning_rate=2e-5 --num_train_epochs=4.0 --output_dir=../output/output_2e5_4epo_176ml_weighted_extra64_1layer256_si/ --do_predict=true --swap_input=true --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=256 >> ../log/2e5_4epo_176ml_weighted_extra64_1layer256_si.log 2>&1 &

CUDA_VISIBLE_DEVICES=6 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=182 --train_batch_size=16 --predict_batch_size=16 --learning_rate=2e-5 --num_train_epochs=3.0 --output_dir=../output/output_2e5_3epo_182ml_weighted_extra64_1layer256/ --do_predict=true --swap_input=false --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=256 >> ../log/2e5_3epo_182ml_weighted_extra64_1layer256.log 2>&1 &

CUDA_VISIBLE_DEVICES=7 nohup python run_classifier_v3.py --task_name=WSDM --do_train=true --do_eval=false --data_dir=$WSDM_DIR --vocab_file=$BERT_BASE_DIR/vocab.txt --bert_config_file=$BERT_BASE_DIR/bert_config.json --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt --max_seq_length=182 --train_batch_size=16 --predict_batch_size=16 --learning_rate=2e-5 --num_train_epochs=3.0 --output_dir=../output/output_2e5_3epo_182ml_weighted_extra64_1layer256_si/ --do_predict=true --swap_input=true --use_class_weights=true --extra_dense_size=64 --extra_train_tensor=$WSDM_DIR/X_64.npy --extra_test_tensor=$WSDM_DIR/X_test_64.npy --extra_num_layers=1 --extra_hidden_units=256 >> ../log/2e5_3epo_182ml_weighted_extra64_1layer256_si.log 2>&1 &
